import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/page/Header";
import Footer from "@/components/page/Footer";
import Banner from "@/components/page/Banner";
import Programs from "@/components/page/Programs";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Next js Project",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="flex flex-col min-h-screen">
        <Header />
        <main className="grow">{children}</main>
        <div className="px-0.5 py-5">
          <Banner />
        </div>
        <div className="w-full hidden md:flex justify-center gap-4 text-5xl p-5">
          ✨⚽✨
          <span className="animate-bounce inline-block">⚽</span>
          ✨⚽✨⚽✨
          <span className="animate-bounce inline-block text-yellow-400">
            ⚽
          </span>
          ✨⚽✨⚽✨
          <span className="inline-block text-red-400">⚽✨✨</span>
          <span className="animate-bounce text-green-400">⚽</span>
        </div>
        <Footer />
      </body>
    </html>
  );
}
